---

- name: apt cache update & upgrade
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: full
  when: ansible_facts.os_family == "Debian"

- name: apt install packages
  ansible.builtin.apt:
    name:
      - mongodb
      - jsvc
      - curl
      - openjdk-8-jre-headless
    state: present
    cache_valid_time: 3600
  when: ansible_facts.os_family == "Debian"

- name: Ensure mongo is runnig on debian.
  ansible.builtin.service:
    name: mongodb
    state: started
    enabled: true
  when: ansible_facts.os_family == "Debian"

- name: is mongodb installed
  ansible.builtin.command: which mongodb
  failed_when: false
  changed_when: false
  check_mode: false
  register: mongo_preset

- name: is Omada installed
  ansible.builtin.command: which tpeap
  failed_when: false
  changed_when: false
  check_mode: false
  register: omada_preset
