---
- name: Install Omada SDN controller
  hosts: all
  become: true

  pre_tasks:
    - name: Vars
      ansible.builtin.include_vars: vars.yml

    - name: Install packages
      ansible.builtin.import_tasks: tasks/packages.yml

  tasks:
    - name: Download Controller from tplink
      ansible.builtin.import_tasks: tasks/setup.yml
      when: omada_preset.rc == 1

    - name: Install Omada
      ansible.builtin.import_tasks: tasks/omada.yml
      when: omada_preset.rc == 1
